name: 'Markdown'

on:
  push:
    paths:
      - 'docs/**'
      - '**.md'
    branches:
    - main
  pull_request:
    paths:
    - 'docs/**'
    - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1