name: detect-secrets

on: [push]

jobs:
  secrets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Detect Secrets
      run:
        pip install detect-secrets
        detect-secrets scan > .secrets.baseline
        detect-secrets -v audit .secrets.baseline